# We gebruiken .yml i.p.v. .json als format voor configuratie van Markdown linter
# Zie voorbeelden https://github.com/DavidAnson/markdownlint/blob/main/schema/.markdownlint.yaml

# Default state for all rules
default: true

no-inline-html: #MD033:
  allowed_elements:
    - img
    - br
    - hr
    - div
    - figcaption
    - em

line-length: #MD013
  false