@startuml class
class java.rmi.registry as "Registry"
interface java.rmi.Remote as "Remote"

interface hello.hello as "HelloRmiInterface" {
    sayHello(): String
}
class hello.server as "HelloRmiServer" {
    {static} main(args: String[]): void 
}
class hello.client as "HelloRmiClient" {
    {static} main(args: String[]): void 
}

java.rmi.Remote --|> hello.hello
hello.hello <|. server
client ..> server
client ..> registry
server ..> registry
@enduml
