@startuml sequence
autonumber
skinparam sequenceMessageAlign center
hide footbox

participant client as "client: HelloRmiClient"
entity stub as "proxy: HelloRmiInterface"
collections registry as "RmiRegistry (//static//)"
entity skeleton as "skeleton: HelloRmiInterface"
participant server as "server: HelloRmiServer"

server -> registry: createRegistry(1099)
registry -> server: registry

server -> registry: lookup("rmi101")
registry --> server: skeleton

client -> registry: getRegistry(1099)
registry -> client: registry

client -> registry: bind("rmi101)
registry -> client: proxy

||| 

client -> stub: sayHallo()
stub -> server: sayHello() <tcp>

server --> stub: "Hello World <:1f600:>"
stub --> client :"Hello World <:1f600:>"
@enduml